#!/usr/bin/env node
/**
 * Generates harness-specific agent files from the single source in `.agents/`.
 *
 *   .agents/agents/<name>.md   ->  .claude/agents/<name>.md
 *                              ->  .github/agents/<name>.agent.md
 *   .agents/skills/<name>/**   ->  .claude/skills/<name>/**   (Claude Code doesn't read .agents/skills)
 *   AGENTS.md review-rules     ->  .github/copilot-instructions.md (Copilot code review reads only this)
 *
 * Usage: node scripts/sync-agents.mjs          write generated files
 *        node scripts/sync-agents.mjs --check  exit 1 if anything is missing, stale or extra
 *
 * Symlinks are deliberately not used: this repo has core.symlinks=false, and Windows
 * checkouts turn committed symlinks into plain text files. See docs/adr/0002-agents-directory.md.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const SRC_AGENTS = '.agents/agents';
const SRC_SKILLS = '.agents/skills';
const OUT_CLAUDE_AGENTS = '.claude/agents';
const OUT_CLAUDE_SKILLS = '.claude/skills';
const OUT_COPILOT_AGENTS = '.github/agents';
const OUT_COPILOT_INSTRUCTIONS = '.github/copilot-instructions.md';

const generatedNote = (source) =>
  `<!-- GENERATED by scripts/sync-agents.mjs from ${source}. Do not edit; edit the source and run \`npm run agents:sync\`. -->`;

// ---- Tiny frontmatter parser (flat keys, inline arrays, booleans, quoted strings) ----------

function parseFrontmatter(text, file) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text);
  if (!m) throw new Error(`${file}: missing frontmatter`);
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const kv = /^([\w-]+):\s*(.*)$/.exec(line);
    if (!kv) throw new Error(`${file}: unsupported frontmatter line "${line}"`);
    data[kv[1]] = parseValue(kv[2].trim());
  }
  return { data, body: m[2] };
}

function parseValue(raw) {
  if (raw === 'true' || raw === 'false') return raw === 'true';
  if (raw.startsWith('[') && raw.endsWith(']')) {
    const inner = raw.slice(1, -1).trim();
    return inner ? inner.split(',').map((s) => unquote(s.trim())) : [];
  }
  return unquote(raw);
}

const unquote = (s) => (/^(["']).*\1$/.test(s) ? s.slice(1, -1) : s);
const yamlString = (s) => JSON.stringify(s);
const yamlList = (items) => `[${items.map((i) => yamlString(i)).join(', ')}]`;

// ---- Tool mapping ---------------------------------------------------------------------------
// Neutral tool names used in .agents/agents: read, search, edit, shell, browser, or `all`.
// Browser tools have different names in every harness, so an agent that needs a browser
// gets `all` (the field is omitted and the harness grants its full tool set).

const CLAUDE_TOOLS = { read: ['Read'], search: ['Grep', 'Glob'], edit: ['Edit', 'Write'], shell: ['Bash'] };
const COPILOT_TOOLS = { read: ['read'], search: ['search'], edit: ['edit'], shell: ['execute'] };

function mapTools(tools, table, file) {
  if (tools === 'all' || tools === undefined) return null;
  return tools.flatMap((t) => {
    if (!table[t]) throw new Error(`${file}: tool "${t}" can't be mapped; use tools: all`);
    return table[t];
  });
}

// ---- Renderers ------------------------------------------------------------------------------

function renderClaudeAgent(a, source) {
  const fm = [`name: ${a.name}`, `description: ${yamlString(a.description)}`];
  const tools = mapTools(a.tools, CLAUDE_TOOLS, source);
  if (tools) fm.push(`tools: ${tools.join(', ')}`);
  if (a.skills?.length) fm.push(`skills: ${yamlList(a.skills)}`);
  return `---\n${fm.join('\n')}\n---\n\n${generatedNote(source)}\n\n${a.body.trim()}\n`;
}

function renderCopilotAgent(a, source) {
  const fm = [`name: ${yamlString(a.name)}`, `description: ${yamlString(a.description)}`];
  const tools = mapTools(a.tools, COPILOT_TOOLS, source);
  if (tools) fm.push(`tools: ${yamlList(tools)}`);
  fm.push(`user-invocable: ${a['user-invocable'] !== false}`);
  // Specialists never delegate further; the architect (main session) owns all handoffs.
  fm.push('agents: []');
  const skills = a.skills?.length
    ? `\n\nSkills for this role (in \`.agents/skills/\`): ${a.skills.map((s) => `\`${s}\``).join(', ')}. Load them before starting.`
    : '';
  return `---\n${fm.join('\n')}\n---\n\n${generatedNote(source)}${skills}\n\n${a.body.trim()}\n`;
}

function renderSkillFile(text, source, isSkillMd) {
  if (!isSkillMd) return text;
  const { body } = parseFrontmatter(text, source); // validates frontmatter exists
  const head = text.slice(0, text.length - body.length).replace(/\r?\n?$/, '\n');
  return `${head}\n${generatedNote(source)}\n\n${body.trimStart()}`;
}

function renderCopilotInstructions() {
  const text = read('AGENTS.md');
  const m = /<!-- review-rules:start -->([\s\S]*?)<!-- review-rules:end -->/.exec(text);
  if (!m) throw new Error('AGENTS.md: missing <!-- review-rules:start/end --> markers');
  return `${generatedNote('AGENTS.md (review-rules section)')}

# Copilot instructions

These are the repository rules code review must enforce. The full rules, commands and agent
workflow are in [AGENTS.md](../AGENTS.md); architecture decisions are in [docs/adr/](../docs/adr/).

${rebaseLinks(m[1].trim(), '../')}
`;
}

/** Relative Markdown links in AGENTS.md point from the repo root; re-point them for a file one level down. */
const rebaseLinks = (md, prefix) =>
  md.replace(/\]\((?!https?:|#|\/|\.\.\/)([^)]+)\)/g, (_, target) => `](${prefix}${target})`);

// ---- File plumbing --------------------------------------------------------------------------

const abs = (p) => join(ROOT, p);
const read = (p) => readFileSync(abs(p), 'utf8');
const norm = (s) => s.replace(/\r\n/g, '\n');
const toPosix = (p) => p.split(sep).join('/');

function walk(dir) {
  if (!existsSync(abs(dir))) return [];
  return readdirSync(abs(dir)).flatMap((entry) => {
    const p = `${dir}/${entry}`;
    return statSync(abs(p)).isDirectory() ? walk(p) : [p];
  });
}

function buildOutputs() {
  const outputs = new Map();

  for (const file of walk(SRC_AGENTS).filter((f) => f.endsWith('.md'))) {
    const { data, body } = parseFrontmatter(read(file), file);
    for (const key of ['name', 'description']) {
      if (!data[key]) throw new Error(`${file}: frontmatter needs "${key}"`);
    }
    const agent = { ...data, body };
    outputs.set(`${OUT_CLAUDE_AGENTS}/${data.name}.md`, renderClaudeAgent(agent, file));
    outputs.set(`${OUT_COPILOT_AGENTS}/${data.name}.agent.md`, renderCopilotAgent(agent, file));
  }

  for (const file of walk(SRC_SKILLS)) {
    const rel = toPosix(relative(abs(SRC_SKILLS), abs(file)));
    outputs.set(`${OUT_CLAUDE_SKILLS}/${rel}`, renderSkillFile(read(file), file, rel.endsWith('/SKILL.md')));
  }

  outputs.set(OUT_COPILOT_INSTRUCTIONS, renderCopilotInstructions());
  return outputs;
}

// ---- Main -----------------------------------------------------------------------------------

const outputs = buildOutputs();
const managed = [OUT_CLAUDE_AGENTS, OUT_CLAUDE_SKILLS, OUT_COPILOT_AGENTS].flatMap(walk);
const extra = managed.filter((f) => !outputs.has(f));
const stale = [...outputs].filter(([p, c]) => !existsSync(abs(p)) || norm(read(p)) !== norm(c)).map(([p]) => p);

if (CHECK) {
  if (stale.length || extra.length) {
    for (const p of stale) console.error(`out of date: ${p}`);
    for (const p of extra) console.error(`not generated from .agents/: ${p}`);
    console.error('\nGenerated agent files drifted from .agents/. Run `npm run agents:sync` and commit.');
    process.exit(1);
  }
  console.log(`agents: ${outputs.size} generated files up to date`);
} else {
  for (const p of extra) rmSync(abs(p));
  for (const p of stale) {
    mkdirSync(dirname(abs(p)), { recursive: true });
    writeFileSync(abs(p), outputs.get(p));
  }
  console.log(`agents: wrote ${stale.length}, removed ${extra.length}, ${outputs.size} total`);
}
